[[Graphite2]]
arch = "aarch64"
git-tree-sha1 = "29a1ad425d1c44162c7dd9ba691a1769cd4e84f7"
os = "macos"

    [[Graphite2.download]]
    sha256 = "35b6c4cc27051607c0ce6228ca9b4eeb654f9b1288bf44e37bc02833bdbd26a6"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.aarch64-apple-darwin.tar.gz"
[[Graphite2]]
arch = "aarch64"
git-tree-sha1 = "518986880cb7a2cf8eaca40fce6bec82c78df3a9"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "13f54d743b4da8e104f882dbdbbf701f1f39a6b195c7ba8eaada054265aa66ec"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.aarch64-linux-gnu.tar.gz"
[[Graphite2]]
arch = "aarch64"
git-tree-sha1 = "59a8dd9b6967b4211db6dadd110f4ef5b2468b1d"
libc = "musl"
os = "linux"

    [[Graphite2.download]]
    sha256 = "3b86e181ce11ddc63e08c0b32b3b41959f4661eee9ae6f70595f926b12351641"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.aarch64-linux-musl.tar.gz"
[[Graphite2]]
arch = "aarch64"
git-tree-sha1 = "0ee6c3839f2f5fe8ffc0cb791734a08f1db9713e"
os = "freebsd"

    [[Graphite2.download]]
    sha256 = "bd4276b1de00593db3294c26099bb9022c24ff980dcd8e44c52987e00ef785cd"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.aarch64-unknown-freebsd.tar.gz"
[[Graphite2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a08aab3eeb7a0a9cca5dbb04e0907f168d296dd4"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "350621a1e5d343a804c843b8c319db8f2e4dc2050ca16843975856a64b3d3028"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.armv6l-linux-gnueabihf.tar.gz"
[[Graphite2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "27e3b6757b8c680aa87497031d161278c55025ae"
libc = "musl"
os = "linux"

    [[Graphite2.download]]
    sha256 = "35023cce54fb5d8b7dbaf22fc68755e99d2cdbc316f851bc0cff7ee0853f5e41"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.armv6l-linux-musleabihf.tar.gz"
[[Graphite2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a0b6087646b7358fb214d02244d610b23401b36c"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "17a25b0d9367a6bc9c5d87d7b3f928ea768c6472679674f1bebec8095c7bda33"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.armv7l-linux-gnueabihf.tar.gz"
[[Graphite2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8c10ce74effccf766ce652f8085a24c8c02a0209"
libc = "musl"
os = "linux"

    [[Graphite2.download]]
    sha256 = "800432487c5a3ecea3651d68cbc5dbeb54962fcda81a3815775357728202b030"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.armv7l-linux-musleabihf.tar.gz"
[[Graphite2]]
arch = "i686"
git-tree-sha1 = "85cf079d3839f0448ca5d3c0bc27ade383e0ec67"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "15e3b4347c21741dbf21ce676c2ddd279cfbe693825e8bdde34f695d4f843fd9"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.i686-linux-gnu.tar.gz"
[[Graphite2]]
arch = "i686"
git-tree-sha1 = "64532c84ea39708097430ed8a64957ee1c73b364"
libc = "musl"
os = "linux"

    [[Graphite2.download]]
    sha256 = "5a42ece4556c8841fee5d757ba62878b94c50a51a95977db26b146ee955e1459"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.i686-linux-musl.tar.gz"
[[Graphite2]]
arch = "i686"
git-tree-sha1 = "c81cfccb5914b89e38b751452ed7cd3d220cecfd"
os = "windows"

    [[Graphite2.download]]
    sha256 = "c7b19667a0c3a3fe8246b9810c1c52efa8b4de2f03b3f9cc6fe742c47fb1cb2f"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.i686-w64-mingw32.tar.gz"
[[Graphite2]]
arch = "powerpc64le"
git-tree-sha1 = "8a51dae10a64167cc86339f59783dec500cc106b"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "0cf9cf11896e0e56607ed5317c044d8309fa585d2d3d944143b51d23912e3e6e"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.powerpc64le-linux-gnu.tar.gz"
[[Graphite2]]
arch = "riscv64"
git-tree-sha1 = "a8fd7dee7ff731db0df873eca4306f974285ef22"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "4737dbc62d8b25f4827158e21865b2ac1ac72d4da735b6dc33c49c75fc21d2ea"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.riscv64-linux-gnu.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "3f205b55e8a2b92677660464088cd5b66e6c9b18"
os = "macos"

    [[Graphite2.download]]
    sha256 = "f387368417ff26ae3a68adc11405b9ca6834e562e6cf13f48c365e5271df6b99"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.x86_64-apple-darwin.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "bb732bf2243761d1f4fea9c69f6a0f38afbc9674"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "2b57237e48fc48f9c54b7a3d5d9a903dc38f5e9be32d961737f7fc7cbe28ef9f"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.x86_64-linux-gnu.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "0aa6d375977c13cbde0b5221a03647612e30ee1c"
libc = "musl"
os = "linux"

    [[Graphite2.download]]
    sha256 = "ebd6b71b75f00a8618c06d01429ebb682ba6499cd4b7e155b04b6e990c8838b0"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.x86_64-linux-musl.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "4946af8f392d065a3526931f8e6874165ecb830b"
os = "freebsd"

    [[Graphite2.download]]
    sha256 = "42968f5828b0459ffb6a3c6552996ed7f1ea676291b415d02e0e73d2da7e4f00"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.x86_64-unknown-freebsd.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "31f1c628431deed47d80cd6eaf6d335352f87c9f"
os = "windows"

    [[Graphite2.download]]
    sha256 = "452ecddf7fb4972650436f4642166a09962b7125779a854de48741b83763b863"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.16+0/Graphite2.v1.3.16.x86_64-w64-mingw32.tar.gz"
