[[Graphite2]]
arch = "aarch64"
git-tree-sha1 = "833d087000ca72f2308636b8b21e83d8a7eab524"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "7decf98b70ad43b1eeccdfc578ed146edcbed3d013d960595b598538e087a920"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+3/Graphite2.v1.3.13.aarch64-linux-gnu.tar.gz"
[[Graphite2]]
arch = "aarch64"
git-tree-sha1 = "ab8bbc21ce9e2e3fd19976f8d00cbbb5811afbc3"
libc = "musl"
os = "linux"

    [[Graphite2.download]]
    sha256 = "f5e7855ad3118655898459382f09fb9f5ffd1d621525d84404dddcd2d96af456"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+3/Graphite2.v1.3.13.aarch64-linux-musl.tar.gz"
[[Graphite2]]
arch = "armv7l"
git-tree-sha1 = "bac48b59dcd19ae79ead48d501761a6d27149157"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "fb13e8a248dc2493d98b45529105f5f5c519c3b63bfcc8720e1a488f5a8bbc59"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+3/Graphite2.v1.3.13.armv7l-linux-gnueabihf.tar.gz"
[[Graphite2]]
arch = "armv7l"
git-tree-sha1 = "31ab25cc28ada8b729d12eabc89737f00a491e5b"
libc = "musl"
os = "linux"

    [[Graphite2.download]]
    sha256 = "27e39acfcffbcfbaaf30e5fc1644e8dc0cb31d92b21e0859c0bd75990c24fe4f"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+3/Graphite2.v1.3.13.armv7l-linux-musleabihf.tar.gz"
[[Graphite2]]
arch = "i686"
git-tree-sha1 = "46225ba1870d0f331228baac93d15a83936d4d26"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "d91737a55cb55fbcd1e4b9c34039d1ad4c6c9d5b180798a4ae0bcd7fd2595925"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+3/Graphite2.v1.3.13.i686-linux-gnu.tar.gz"
[[Graphite2]]
arch = "i686"
git-tree-sha1 = "799024bfac21093bac0cdf27d1b5a21847c0abfe"
libc = "musl"
os = "linux"

    [[Graphite2.download]]
    sha256 = "3d6cd4a692916f53b38c29f6b18ff932fe07cd2908d50a355dc16a7f70774658"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+3/Graphite2.v1.3.13.i686-linux-musl.tar.gz"
[[Graphite2]]
arch = "i686"
git-tree-sha1 = "ab4276d460dd7f501a0b9643c58a6dd54bc476ce"
os = "windows"

    [[Graphite2.download]]
    sha256 = "d65ccc35e079a05129d4f0c5e311bd681de4860b576352021820dacea2b0c71d"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+3/Graphite2.v1.3.13.i686-w64-mingw32.tar.gz"
[[Graphite2]]
arch = "powerpc64le"
git-tree-sha1 = "fd283f10560235e90871b2d17ca2fd98ea78f084"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "8bf71f6b3033d2a3cfe82ad3d9ef782591561bff6f6fa0f49840e718e086663d"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+3/Graphite2.v1.3.13.powerpc64le-linux-gnu.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "0c063b1aef124b99659e1604675f2dce871e7e97"
os = "macos"

    [[Graphite2.download]]
    sha256 = "608fa2d2b030cfdb787a687c03e72b6fa9acfad7bde49039639c191f57d477af"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+3/Graphite2.v1.3.13.x86_64-apple-darwin14.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "ba13d4f7e85858768358cb37cdc00e8c7acb2cca"
libc = "glibc"
os = "linux"

    [[Graphite2.download]]
    sha256 = "11a186cb20bac7ca4cd5af9565e4067244d689471cf3c3b0409d0409066ffe25"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+3/Graphite2.v1.3.13.x86_64-linux-gnu.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "7548e0416962a235fce2c0a7f5ededdde8f447b8"
libc = "musl"
os = "linux"

    [[Graphite2.download]]
    sha256 = "f325db67dff589108c86b037ec4e449c7b8a431ea49c7ec2b2a873df6e2601b4"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+3/Graphite2.v1.3.13.x86_64-linux-musl.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "77c5ab3d3d74f9ffa872884c736154fcf3c18908"
os = "freebsd"

    [[Graphite2.download]]
    sha256 = "6a78a63797501d1f15421852cd34cac8f2b830e5f3b9bed6dcc963beeff6dcac"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+3/Graphite2.v1.3.13.x86_64-unknown-freebsd11.1.tar.gz"
[[Graphite2]]
arch = "x86_64"
git-tree-sha1 = "9f93bdbf4d57ef81a34d855869ebda0244b7e0f2"
os = "windows"

    [[Graphite2.download]]
    sha256 = "271ec150f4a210d543d52d54f7a10f209deee162de4d481ecb9818c8922656ae"
    url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.13+3/Graphite2.v1.3.13.x86_64-w64-mingw32.tar.gz"
